export const GatedContent = [
  {
    type: "constructor",
    inputs: [
      { name: "_badge", type: "address", internalType: "address" },
      {
        name: "_subscriptionManager",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BRONZE_VOTE_WEIGHT",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "EARLY_VOTER_REWARD_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "EARLY_VOTER_SLOTS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "GOLD_VOTE_WEIGHT",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SILVER_VOTE_WEIGHT",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "badge",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract TieredBadge" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimVoterReward",
    inputs: [{ name: "postId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createExclusivePost",
    inputs: [
      { name: "_minTier", type: "uint256", internalType: "uint256" },
      { name: "_contentHash", type: "string", internalType: "string" },
      { name: "_threshold", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "creatorPosts",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deletePost",
    inputs: [{ name: "postId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "earlyVoterRewards",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "voter", type: "address", internalType: "address" },
      { name: "rewardAmount", type: "uint256", internalType: "uint256" },
      { name: "claimed", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "exclusivePosts",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "postId", type: "uint256", internalType: "uint256" },
      { name: "creator", type: "address", internalType: "address" },
      { name: "minTierRequired", type: "uint256", internalType: "uint256" },
      { name: "contentHash", type: "string", internalType: "string" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      { name: "isPublic", type: "bool", internalType: "bool" },
      { name: "viralScore", type: "uint256", internalType: "uint256" },
      { name: "conversionThreshold", type: "uint256", internalType: "uint256" },
      { name: "currentVotes", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fundRewardPool",
    inputs: [{ name: "postId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "getCreatorPosts",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEarlyVoterRewards",
    inputs: [{ name: "postId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct GatedContent.EarlyVoterReward[]",
        components: [
          { name: "voter", type: "address", internalType: "address" },
          { name: "rewardAmount", type: "uint256", internalType: "uint256" },
          { name: "claimed", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEarlyVoters",
    inputs: [{ name: "postId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPost",
    inputs: [{ name: "postId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GatedContent.ExclusivePost",
        components: [
          { name: "postId", type: "uint256", internalType: "uint256" },
          { name: "creator", type: "address", internalType: "address" },
          { name: "minTierRequired", type: "uint256", internalType: "uint256" },
          { name: "contentHash", type: "string", internalType: "string" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "isPublic", type: "bool", internalType: "bool" },
          { name: "viralScore", type: "uint256", internalType: "uint256" },
          {
            name: "conversionThreshold",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "currentVotes", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPostVoters",
    inputs: [{ name: "postId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPosts",
    inputs: [{ name: "postIds", type: "uint256[]", internalType: "uint256[]" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct GatedContent.ExclusivePost[]",
        components: [
          { name: "postId", type: "uint256", internalType: "uint256" },
          { name: "creator", type: "address", internalType: "address" },
          { name: "minTierRequired", type: "uint256", internalType: "uint256" },
          { name: "contentHash", type: "string", internalType: "string" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "isPublic", type: "bool", internalType: "bool" },
          { name: "viralScore", type: "uint256", internalType: "uint256" },
          {
            name: "conversionThreshold",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "currentVotes", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVoterInfo",
    inputs: [
      { name: "postId", type: "uint256", internalType: "uint256" },
      { name: "voter", type: "address", internalType: "address" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct GatedContent.VoterInfo",
        components: [
          { name: "hasVoted", type: "bool", internalType: "bool" },
          { name: "voteOrder", type: "uint256", internalType: "uint256" },
          { name: "votedAt", type: "uint256", internalType: "uint256" },
          { name: "tierAtVote", type: "uint256", internalType: "uint256" },
          { name: "rewardClaimed", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVotingProgress",
    inputs: [{ name: "postId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "currentVotes", type: "uint256", internalType: "uint256" },
      { name: "threshold", type: "uint256", internalType: "uint256" },
      { name: "viralScore", type: "uint256", internalType: "uint256" },
      { name: "percentComplete", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasAccess",
    inputs: [
      { name: "_user", type: "address", internalType: "address" },
      { name: "_postId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasAccessBatch",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "postIds", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [{ name: "", type: "bool[]", internalType: "bool[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "postCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "postRewardPool",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "postVoters",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "subscriptionManager",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract SubscriptionManager",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "voteForPublicRelease",
    inputs: [{ name: "_postId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "voterInfo",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "hasVoted", type: "bool", internalType: "bool" },
      { name: "voteOrder", type: "uint256", internalType: "uint256" },
      { name: "votedAt", type: "uint256", internalType: "uint256" },
      { name: "tierAtVote", type: "uint256", internalType: "uint256" },
      { name: "rewardClaimed", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "votes",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PostCreated",
    inputs: [
      {
        name: "postId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "minTierRequired",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "conversionThreshold",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "contentHash",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PostDeleted",
    inputs: [
      {
        name: "postId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PostWentPublic",
    inputs: [
      {
        name: "postId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalVotes",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "finalViralScore",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RewardClaimed",
    inputs: [
      {
        name: "postId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "voter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VoteCast",
    inputs: [
      {
        name: "postId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "voter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "voteOrder",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "voterTier",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "viralScore",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "currentVotes",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "VoterRewardDistributed",
    inputs: [
      {
        name: "postId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "voter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "rewardAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadyPublic", inputs: [] },
  { type: "error", name: "AlreadyVoted", inputs: [] },
  { type: "error", name: "InsufficientTier", inputs: [] },
  { type: "error", name: "InvalidThreshold", inputs: [] },
  { type: "error", name: "NoRewardToClaim", inputs: [] },
  { type: "error", name: "NotCreator", inputs: [] },
  { type: "error", name: "NotSubscribed", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "PostNotFound", inputs: [] },
  { type: "error", name: "RewardAlreadyClaimed", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
];
