export const subscriptionManagerAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_badge", type: "address", internalType: "address" },
      { name: "_feeRecipient", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "TIER_BRONZE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TIER_GOLD",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TIER_SILVER",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "badge",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract TieredBadge" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelSubscription",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "checkAccess",
    inputs: [
      { name: "_creator", type: "address", internalType: "address" },
      { name: "_subscriber", type: "address", internalType: "address" },
      { name: "_postId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "configureTiers",
    inputs: [
      { name: "bronzePrice", type: "uint256", internalType: "uint256" },
      { name: "silverPrice", type: "uint256", internalType: "uint256" },
      { name: "goldPrice", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "creatorByIndex",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creatorCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creatorRevenue",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creators",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      { name: "wallet", type: "address", internalType: "address" },
      { name: "handle", type: "string", internalType: "string" },
      { name: "name", type: "string", internalType: "string" },
      { name: "profileURI", type: "string", internalType: "string" },
      { name: "tierIds", type: "uint256", internalType: "uint256" },
      { name: "isActive", type: "bool", internalType: "bool" },
      { name: "totalSubscribers", type: "uint256", internalType: "uint256" },
      { name: "creatorIndex", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deactivateCreator",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deactivateTier",
    inputs: [{ name: "tier", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "feeRecipient",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCreator",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct SubscriptionManager.Creator",
        components: [
          { name: "wallet", type: "address", internalType: "address" },
          { name: "handle", type: "string", internalType: "string" },
          { name: "name", type: "string", internalType: "string" },
          { name: "profileURI", type: "string", internalType: "string" },
          { name: "tierIds", type: "uint256", internalType: "uint256" },
          { name: "isActive", type: "bool", internalType: "bool" },
          {
            name: "totalSubscribers",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "creatorIndex", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCreatorByHandle",
    inputs: [{ name: "handle", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCreatorRevenue",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPendingWithdraw",
    inputs: [{ name: "creator", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubscription",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "subscriber", type: "address", internalType: "address" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct SubscriptionManager.Subscription",
        components: [
          { name: "subscriber", type: "address", internalType: "address" },
          { name: "tierId", type: "uint256", internalType: "uint256" },
          { name: "startDate", type: "uint256", internalType: "uint256" },
          { name: "renewalDate", type: "uint256", internalType: "uint256" },
          { name: "isActive", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubscriptionTier",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "creator", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTierConfig",
    inputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "tier", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct SubscriptionManager.TierConfig",
        components: [
          { name: "name", type: "string", internalType: "string" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "duration", type: "uint256", internalType: "uint256" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "metadataURI", type: "string", internalType: "string" },
          { name: "maxSupply", type: "uint256", internalType: "uint256" },
          { name: "minHoldTime", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "handleToCreator",
    inputs: [{ name: "", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasActiveSubscription",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "creator", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingPlatformFees",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingWithdraw",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "platformFeeBps",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registerCreator",
    inputs: [
      { name: "_handle", type: "string", internalType: "string" },
      { name: "_name", type: "string", internalType: "string" },
      { name: "_profileURI", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renewSubscription",
    inputs: [{ name: "_creator", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFeeRecipient",
    inputs: [
      { name: "newRecipient", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPlatformFee",
    inputs: [{ name: "newFeeBps", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "subscribe",
    inputs: [
      { name: "_creator", type: "address", internalType: "address" },
      { name: "_tierId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "subscriptions",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "subscriber", type: "address", internalType: "address" },
      { name: "tierId", type: "uint256", internalType: "uint256" },
      { name: "startDate", type: "uint256", internalType: "uint256" },
      { name: "renewalDate", type: "uint256", internalType: "uint256" },
      { name: "isActive", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tierConfigs",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "price", type: "uint256", internalType: "uint256" },
      { name: "duration", type: "uint256", internalType: "uint256" },
      { name: "isActive", type: "bool", internalType: "bool" },
      { name: "metadataURI", type: "string", internalType: "string" },
      { name: "maxSupply", type: "uint256", internalType: "uint256" },
      { name: "minHoldTime", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "upgradeSubscription",
    inputs: [
      { name: "_creator", type: "address", internalType: "address" },
      { name: "_newTierId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawPlatformFees",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ContentUnlocked",
    inputs: [
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "postId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "subscriber",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CreatorRegistered",
    inputs: [
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "handle",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "creatorIndex",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlatformFeesWithdrawn",
    inputs: [
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Subscribed",
    inputs: [
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "subscriber",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "tierId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "startDate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "renewalDate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SubscriptionCancelled",
    inputs: [
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "subscriber",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SubscriptionRenewed",
    inputs: [
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "subscriber",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newRenewalDate",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SubscriptionUpgraded",
    inputs: [
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "subscriber",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "oldTier",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newTier",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TierConfigured",
    inputs: [
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "tier", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "name", type: "string", indexed: false, internalType: "string" },
      {
        name: "price",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "duration",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AlreadySubscribed", inputs: [] },
  { type: "error", name: "CannotDowngrade", inputs: [] },
  { type: "error", name: "CreatorAlreadyRegistered", inputs: [] },
  { type: "error", name: "CreatorNotActive", inputs: [] },
  { type: "error", name: "CreatorNotFound", inputs: [] },
  { type: "error", name: "HandleAlreadyTaken", inputs: [] },
  { type: "error", name: "HandleTooLong", inputs: [] },
  { type: "error", name: "HandleTooShort", inputs: [] },
  { type: "error", name: "InsufficientPayment", inputs: [] },
  { type: "error", name: "InvalidTier", inputs: [] },
  { type: "error", name: "NotSubscribed", inputs: [] },
  { type: "error", name: "NothingToWithdraw", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "SameTier", inputs: [] },
  { type: "error", name: "SubscriptionExpired", inputs: [] },
  { type: "error", name: "TierNotConfigured", inputs: [] },
  { type: "error", name: "WithdrawFailed", inputs: [] },
];
